export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_SELECTED = 'DELETE_SELECTED';
export const DELETE_COMPLETED = 'DELETE_COMPLETED';
export const SELECT_DESELECT_ALL = 'SELECT_DESELECT_ALL';
export const INPUT_TEXT_CHANGE = 'INPUT_TEXT_CHANGE'
export const CHECKED_STATUS_CHANGE = 'CHECKED_STATUS_CHANGE';
export const COMPLETED_STATUS_CHANGE = 'COMPLETED_STATUS_CHANGE';